# Generated by Django 5.2.5 on 2025-12-03 20:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Insumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(max_length=50)),
                ('cantidad', models.IntegerField()),
                ('marca', models.CharField(blank=True, max_length=50)),
                ('color', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('precio_base', models.IntegerField()),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='productos/')),
                ('destacado', models.BooleanField(default=False)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente_nombre', models.CharField(max_length=100)),
                ('cliente_email', models.EmailField(max_length=254)),
                ('cliente_telefono', models.CharField(max_length=20)),
                ('descripcion_solicitud', models.TextField()),
                ('imagen_referencia', models.ImageField(blank=True, null=True, upload_to='referencias/')),
                ('fecha_solicitada', models.DateField(blank=True, help_text='Fecha en que el cliente necesita el producto', null=True)),
                ('plataforma', models.CharField(choices=[('WEB', 'Sitio Web'), ('INSTAGRAM', 'Instagram'), ('FACEBOOK', 'Facebook'), ('WHATSAPP', 'WhatsApp'), ('PRESENCIAL', 'Presencial')], default='WEB', max_length=20)),
                ('estado_pedido', models.CharField(choices=[('SOLICITADO', 'Solicitado'), ('APROBADO', 'Aprobado'), ('EN_PROCESO', 'En proceso'), ('REALIZADA', 'Realizada'), ('ENTREGADA', 'Entregada'), ('FINALIZADA', 'Finalizada'), ('CANCELADA', 'Cancelada')], default='SOLICITADO', max_length=20)),
                ('estado_pago', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PARCIAL', 'Parcial'), ('PAGADO', 'Pagado')], default='PENDIENTE', max_length=20)),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('producto_referencia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.producto')),
            ],
        ),
    ]
